### ISSUE TITLE
Please give credit to the sites/people you learned about this from.

### ISSUE THREAD

**Issue by WebBreacher** [asharbinkhalil/khoji#1]
Hey! This is really cool work you did in Python. I think the hashtag OSINT and cyber security communities frown upon not crediting the people/sites where you learned about things.

Your research looks similar to something that Griffin Glynn (https://hatless1der.com/a-snapchat-osint-tip-viewing-bitmoji-changes/) and I blogged about in the past week or two. In fact, I made the BACKMOJI tool that looks really similar to your tool but is in HTML and not Python: https://webbreacher.github.io/osinttools/.

**Comment by asharbinkhalil** [comment]
Sir  I honestly was not aware of your tool. I just skimmed your article and wrote a script t he other day. 
I am really sorry. I gave all the credits everywhere now.

**Comment by WebBreacher** [comment]
Thanks for noting Griffin (and my) work. Always cite where you learned things. It helps others backtrack and learn and it shows that others (Griffin) discovered this first.

Thank you for altering your wording in your readme to reflect this.

**Comment by asharbinkhalil** [comment]
Thank you. I will follow this advice. I also learn from you people.
