### ISSUE TITLE
Attribution on the web page?

### ISSUE THREAD

**Issue by WebBreacher** [asharbinkhalil/khoji#2]
Ashar....I love how you've improved on what @hatless1der and I made! Entering just the Snap username is MUCH easier than our method. Well done!

I see that in your https://github.com/asharbinkhalil/khoji/tree/master repo you have provided Griffin some attribution and linked to his blog post. I noticed in your tweet, you also mention my backmoji tool as inspiration. When I visited your web page (https://khoji.onrender.com/), however, I didn't see any of this attribution and was wondering if you could please add add some as it looks like you are taking credit for not only coding (which you did!) but the original idea too. I would have submitted a PR to do it but the version of the tool here seems to only generate a PDF of the output. 

Thanks and looking forward to seeing more of your tools!

**Comment by asharbinkhalil** [comment]
added credits
![image](https://github.com/asharbinkhalil/khoji/assets/68750622/f49b0460-beb2-4ba6-822c-2508447b5eae)

**Comment by WebBreacher** [comment]
Awesome and thank you!!
