### ISSUE TITLE
Request to Open-Source Your Web Page

### ISSUE THREAD

**Issue by FazCodeFR** [asharbinkhalil/khoji#3]
Hey,

https://khoji.onrender.com/ 

Hope you're doing well! I've been checking out your website and have some cool ideas for improvements. Any chance you'd be open to making the page open source? I'd love to contribute and maybe get others involved too.

Thanks a bunch!

**Comment by asharbinkhalil** [comment]
Ok cool, I just added you in web version repository.

**Comment by asharbinkhalil** [comment]
I made the web version repository public, you can make changes , I will  merge them

**Comment by asharbinkhalil** [comment]
https://github.com/asharbinkhalil/khoji_web
